version: "3"
services:
  app:
    environment:
      - DATABASE_URL=mongodb://mongo:27017/acronym
    container_name: wtf
    restart: always
    build: .
    ports: 
      - "12345:12345"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27018:27017"
